# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html
  configuration: py-ft/docs/conf.py

build:
  os: "ubuntu-20.04"
  apt_packages:
    - cmake
  tools:
    python: "3.10"
    rust: "latest"

python:
  install:
    - requirements: py-ft/docs/requirements.txt
    - method: pip
      path: ./py-ft
#conda:
#    environment: py-ft/docs/environment.yml
