# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html
  configuration: py-ft/docs/conf.py

build:
  os: "ubuntu-22.04"
  apt_packages:
    - cmake
  tools:
    python: "3.10"
  jobs:
    pre_install:
      # Install Rust via rustup to get a recent version
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - . $HOME/.cargo/env
      - rustc --version

python:
  install:
    - requirements: py-ft/docs/requirements.txt
    - method: pip
      path: ./py-ft
#conda:
#    environment: py-ft/docs/environment.yml
