# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html
  configuration: py-ft/docs/conf.py

build:
  os: "ubuntu-20.04"
  apt_packages:
    - cmake
  tools:
    python: "3.12"
    #rust: "1.85"
  jobs:
    create_environment:
      - asdf install rust 1.85
      - asdf global rust 1.85
      #- asdf plugin-add python
      #- asdf install python 3.12
      - asdf global python 3.12

python:
  install:
    - requirements: py-ft/docs/requirements.txt
    - method: pip
      path: ./py-ft
#conda:
#    environment: py-ft/docs/environment.yml
