#theme: jekyll-theme-minimal
#theme: minima
remote_theme: jekyll/minima
logo: /assets/img/fiber_tools_grey.png

minima:
  skin: dark


defaults:
  -
    scope:
      path: "README.md"
    values:
      permalink: "index.html"

exclude:
    - target
    - models
    - dists
    - tmp.*
    - temp
